name: Compile blueprint

on:
  push:
    branches:
      - main # Trigger on pushes to the default branch
  workflow_dispatch: # Allow manual triggering of the workflow from the GitHub Actions interface

# Cancel previous runs if a new commit is pushed to the same PR or branch
concurrency:
  group: ${{ github.ref }}  # Group runs by the ref (branch or PR)
  cancel-in-progress: true  # Cancel any ongoing runs in the same group

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read  # Read access to repository contents
  pages: write    # Write access to GitHub Pages
  id-token: write # Write access to ID tokens

jobs:
  build_project_blueprint:
    runs-on: ubuntu-latest
    # Coq container with mathcomp available
    # See also https://hub.docker.com/r/mathcomp/mathcomp
    container: mathcomp/mathcomp:2.2.0-coq-8.17
    name: Build jscoq project
    steps:
      - name: Workaround permissions issue
        run: sudo chown -R 1000:1000 .

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6

      - name: Install node dependencies
        run: make node_modules

      - name: Build rocq project and generate html files
        run: make

      - name: "Upload website (individual lessons)"
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .  # <--
